# These are supported funding model platforms

ko_fi: jetrocosta
patreon: jetrocosta
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=2CTSTMBJNF6Z6&item_name=Me+ajudar+a+continuar+a+devesenvolver+para+a+comunidade+de+software+livre.&currency_code=BRL
